# Generated by Django 4.2.7 on 2023-11-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('main_title', models.CharField(max_length=2000)),
                ('experience', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('how_to_work', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=250, null=True)),
                ('line_1', models.CharField(max_length=250, null=True)),
                ('line_2', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companylogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_we_are', models.CharField(max_length=2000)),
                ('form_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('Working_Hours', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255)),
                ('location_map', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=250, null=True)),
                ('event', models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('COMPLETATE', 'COMPLETATE')], max_length=20)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True)),
                ('answers', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('dark', 'dark'), ('body', 'body'), ('white', 'white'), ('transparent', 'transparent'), ('light', 'light')], max_length=100)),
                ('facebook', models.CharField(max_length=250, null=True)),
                ('youtube', models.CharField(max_length=250, null=True)),
                ('whatsApp', models.CharField(max_length=250, null=True)),
                ('instagram', models.CharField(max_length=250, null=True)),
                ('telegram', models.CharField(max_length=250, null=True)),
                ('pinterest', models.CharField(max_length=250, null=True)),
                ('twitter', models.CharField(max_length=250, null=True)),
                ('linkedIn', models.CharField(max_length=250, null=True)),
                ('copyright', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='image')),
                ('color', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('dark', 'dark'), ('body', 'body'), ('white', 'white'), ('transparent', 'transparent'), ('light', 'light')], max_length=100)),
                ('number', models.CharField(max_length=12, null=True)),
                ('contant_1', models.CharField(max_length=250, null=True)),
                ('contant_2', models.CharField(max_length=250, null=True)),
                ('contant_3', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=500, null=True)),
                ('keyword', models.CharField(max_length=500, null=True)),
                ('discriptaion', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
    ]
