# Generated by Django 4.2.7 on 2023-11-22 06:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_banner_companylogo_contact_event_faq_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='main_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
